"""Add reactions field to Post model

Revision ID: 2a3539a15ec9
Revises: f9476a63501b
Create Date: 2024-12-14 21:58:30.318705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text  # Import Text explicitly

# revision identifiers, used by Alembic.
revision = '2a3539a15ec9'
down_revision = 'f9476a63501b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reactions', postgresql.JSON(astext_type=Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('reactions')

    # ### end Alembic commands ###
